//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalSurmackiLab04
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationAboutStudent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surnname { get; set; }
        public string StudentIndex { get; set; }
        public string Email { get; set; }
        public int UserNameId { get; set; }
    
        public virtual StudentLogInSystem StudentLogInSystem { get; set; }
    }
}
