//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalSurmackiLab04Zad1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MichalSurmackiLab04Zad01Entities : DbContext
    {
        public MichalSurmackiLab04Zad01Entities()
            : base("name=MichalSurmackiLab04Zad01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductsForSale> ProductsForSales { get; set; }
        public virtual DbSet<SoldProduct> SoldProducts { get; set; }
    }
}
