//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalSurmackiLab04Zad1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldProduct
    {
        public int IDTransaction { get; set; }
        public Nullable<System.DateTime> DateOfTransaction { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
